# ==== Athene Seagrass Config====

units: "config/units.tsv"
wgs_reads: "data/wgs/florida_individual.fq.gz"
output_dir: "results"

# ANGSD & Population Parameters

minMapQ: 30       
minQ: 20          
minMaf: 0.05      
minInd: 4         
snp_pval: 1e-6    
k_values: [2, 3, 4]
