#====Meta-Sheets and Storage Paths==== 

units: "config/units.tsv"
data_parent_dir: "data/"  # Must end with a trailing forward slash!
output_dir: "results"

wgs_reads: "data/wgs/florida_individual.fq.gz"
ref_genome_path: "results/assembly/final_genome.fasta"
pca_output_path: "results/popgen/pcangsd/seagrass_pca.cov"

#====Downstream Analysis Filtering Parameters====

angsd_params:
  minMapQ: 30       
  minQ: 20          
  minMaf: 0.05      
  minInd: 4         
  snp_pval: 1e-6    

admixture:
  k_values:
    - 2
    - 3
    - 4
