# 1. Load the framework environment and sample lists 

include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        # run_assembly: Reference Assembly
        config["ref_genome_path"],
        
        # run_popgen: Downstream population analytics
        config["pca_output_path"],
        expand(
            "results/popgen/ngsadmix/k{k}_admix.qopt", 
            k=config["admixture"]["k_values"]
        )

##### Modules #####

include: "rules/assembly.smk"
include: "rules/popgen.smk"
