project: seagrass_popgen

samples: null #config/samples.tsv

reference:
  fasta: resources/reference/reference.fa

assembly:
  enabled: true   # plug-in point for later

  pacbio_bam: ../CGKMAH250121-1/Data/PacBio_WGS/Halodule_wrightii/m84104_250620_063612_s2.hifi_reads.bc2032.bam #here add the path to your bam file
  species: Halodure_wrightii
  busco_lineage: 
  
  hic_r1: Data/HiC/Halodule-wrightii-1_1.fq.gz
  hic_r2: Data/HiC/Halodule-wrightii-1_2.fq.gz

  threads: 64

mapping:
  mapper: bwa-mem2

filters:
  min_mapq: 30
  min_baseq: 20

angsd:
  gl_model: 1
  minInd: 0.7
  minMapQ: 30
  minQ: 20

admixture:
  K: [1,2,3,4,5,6,7,8,9,10]

threads: 8
